services:
  server:
    build: 
      context: ./api
      dockerfile: Dockerfile
    image: dfc-backend
    container_name: dfc-backend-container
    ports:
      - "8000:8000"

  client:
    build:
      context: ./ui
      dockerfile: Dockerfile
    image: dfc-frontend
    container_name: dfc-frontend-container
    ports:
      - "3000:3000"
    depends_on:
      - server